name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Java Application with Maven
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Upload WAR to S3
        run: |
          aws s3 cp backend/target/app.war s3://my-deploy-bucket/app.war

      - name: Deploy to Tomcat (Private Subnet) via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.TOMCAT_INSTANCE_ID }}" \
            --parameters 'commands=["aws s3 cp s3://my-deploy-bucket/app.war /opt/tomcat/webapps/ROOT.war", "systemctl restart tomcat"]'
